apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-demo-deployment-dev
    env: dev
  name: argocd-demo-deployment-dev
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: argocd-demo-deployment-dev
  strategy: {}
  template:
    metadata:
      labels:
        app: argocd-demo-deployment-dev
    spec:
      containers:
      - image: zulqadara/argocd-demo:v1
        name: argocd-demo
        resources: {}
status: {}
