apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-demo-deployment-prod
    env: prod
  name: argocd-demo-deployment-prod
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-demo-deployment-prod
  strategy: {}
  template:
    metadata:
      labels:
        app: argocd-demo-deployment-prod
    spec:
      containers:
      - image: zulqadara/argocd-demo:v1
        name: argocd-demo
        resources: {}
status: {}